import { useState, type FormEvent } from 'react'
import { useLocation, useNavigate, useSearchParams } from 'react-router-dom'
import { useAuth, type MfaSetup } from '../../auth/AuthContext'
import { ApiError } from '../../lib/api'
import { Button } from '../../components/ui/Button'
import { Field, Input } from '../../components/ui/Input'
import { AuthShell } from './AuthShell'

type Step = 'credentials' | 'otp' | 'setup'

export function LoginPage() {
  const { login, verifyMfa, setupMfa, confirmMfa } = useAuth()
  const navigate = useNavigate()
  const location = useLocation()
  const [searchParams] = useSearchParams()

  const [step, setStep] = useState<Step>('credentials')
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [remember, setRemember] = useState(false)
  const [code, setCode] = useState('')
  const [setup, setSetup] = useState<MfaSetup | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)

  /** Where to land after signing in — the page the guard bounced us from, else home. */
  function resolveTarget(): string {
    const from = (location.state as { from?: string } | null)?.from
    if (typeof from === 'string' && from.startsWith('/')) return from
    const next = searchParams.get('next')
    // Only same-origin paths, so `?next=` can't be used as an open redirect.
    if (next && next.startsWith('/')) return next
    return '/'
  }

  function fail(err: unknown, fallback: string) {
    setError(err instanceof ApiError ? err.message : fallback)
  }

  async function onCredentials(e: FormEvent) {
    e.preventDefault()
    setError(null)
    setBusy(true)
    try {
      const result = await login(username, password, remember)
      if (result === 'ok') {
        navigate(resolveTarget(), { replace: true })
      } else if (result === 'mfa_required') {
        setStep('otp')
      } else {
        // First login — fetch the QR to scan.
        const s = await setupMfa()
        setSetup(s)
        setStep('setup')
      }
    } catch (err) {
      fail(err, 'Login failed. Try again.')
    } finally {
      setBusy(false)
    }
  }

  async function onVerify(e: FormEvent) {
    e.preventDefault()
    setError(null)
    setBusy(true)
    try {
      await verifyMfa(code.trim())
      navigate(resolveTarget(), { replace: true })
    } catch (err) {
      fail(err, 'That code is not valid.')
    } finally {
      setBusy(false)
    }
  }

  async function onConfirmSetup(e: FormEvent) {
    e.preventDefault()
    setError(null)
    setBusy(true)
    try {
      await confirmMfa(code.trim())
      navigate(resolveTarget(), { replace: true })
    } catch (err) {
      fail(err, 'That code is not valid.')
    } finally {
      setBusy(false)
    }
  }

  const errorBox = error && (
    <div className="rounded-[var(--radius-sm)] border border-danger-border bg-danger-bg px-3 py-2 text-sm text-danger-fg">
      {error}
    </div>
  )

  const codeInput = (
    <Field label="Authenticator code">
      <Input
        value={code}
        onChange={(e) => setCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
        inputMode="numeric"
        autoComplete="one-time-code"
        placeholder="123456"
        autoFocus
        required
      />
    </Field>
  )

  // --- Step: enter authenticator code (enrolled user) ---------------------
  if (step === 'otp') {
    return (
      <AuthShell subtitle="Enter the code from your authenticator app">
        <div className="space-y-4 rounded-[var(--radius-lg)] border border-border bg-surface p-6 shadow-sm">
          {errorBox}
          <form onSubmit={onVerify} className="space-y-4">
            {codeInput}
            <Button type="submit" className="w-full" disabled={busy || code.length < 6}>
              {busy ? 'Verifying…' : 'Verify'}
            </Button>
          </form>
        </div>
      </AuthShell>
    )
  }

  // --- Step: first-login enrollment (scan the QR) -------------------------
  if (step === 'setup' && setup) {
    return (
      <AuthShell subtitle="Set up two-factor authentication">
        <div className="space-y-4 rounded-[var(--radius-lg)] border border-border bg-surface p-6 shadow-sm">
          {errorBox}
          <p className="text-sm text-text-secondary">
            Scan this QR code with an authenticator app (Google Authenticator, Authy, 1Password),
            then enter the 6-digit code to finish.
          </p>
          <div
            className="mx-auto h-44 w-44 rounded-[var(--radius-sm)] bg-white p-2 [&_svg]:h-full [&_svg]:w-full"
            // The QR is a self-contained SVG generated by the backend.
            dangerouslySetInnerHTML={{ __html: setup.qr_svg }}
          />
          <p className="text-center text-xs text-text-muted">
            Can't scan? Enter this key manually:
            <br />
            <span className="font-mono break-all text-text-secondary">{setup.secret}</span>
          </p>
          <form onSubmit={onConfirmSetup} className="space-y-4">
            {codeInput}
            <Button type="submit" className="w-full" disabled={busy || code.length < 6}>
              {busy ? 'Confirming…' : 'Confirm & sign in'}
            </Button>
          </form>
        </div>
      </AuthShell>
    )
  }

  // --- Step: username + password ------------------------------------------
  return (
    <AuthShell subtitle="Sign in to continue">
      <div className="space-y-4 rounded-[var(--radius-lg)] border border-border bg-surface p-6 shadow-sm">
        {errorBox}
        <form onSubmit={onCredentials} className="space-y-4">
          <Field label="Username or email">
            <Input
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              autoComplete="username"
              autoFocus
              required
            />
          </Field>

          <Field label="Password">
            <Input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              autoComplete="current-password"
              required
            />
          </Field>

          <label className="flex items-center gap-2 text-sm text-text-secondary">
            <input
              type="checkbox"
              checked={remember}
              onChange={(e) => setRemember(e.target.checked)}
              className="accent-[var(--accent)]"
            />
            Remember me
          </label>

          <Button type="submit" className="w-full" disabled={busy}>
            {busy ? 'Signing in…' : 'Sign in'}
          </Button>
        </form>

        <p className="text-center text-xs text-text-muted">
          Accounts are created by an administrator.
        </p>
      </div>
    </AuthShell>
  )
}
